apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  labels:
    app: cluster-autoscaler
    kubernetes.io/cluster-service: 'true'
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cluster-autoscaler
      kubernetes.io/cluster-service: 'true'
  template:
    metadata:
      labels:
        app: cluster-autoscaler
        kubernetes.io/cluster-service: 'true'
    spec:
      containers:
      - image: '${cluster_autoscaler_image}'
        name: cluster-autoscaler
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        command:
        - ./cluster-autoscaler
        - --v=2
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --scale-down-delay=2m
        - --scale-down-utilization-threshold=0.2
        - --scale-down-unneeded-time=2m
        - --scale-down-unready-time=5m
        - --expander=least-waste
        - --skip-nodes-with-local-storage=false
        # Per-ASG configuration
${per_asg_configuration}
        env:
        - name: AWS_REGION
          value: ${aws_region}
        volumeMounts:
        - name: ssl-certs
          mountPath: /etc/ssl/certs/ca-certificates.crt
          readOnly: true
        imagePullPolicy: Always
      nodeSelector:
        role.node: system
      restartPolicy: Always
      volumes:
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs/ca-certificates.crt
