apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-problem-detector
  namespace: kube-system
  labels:
    run: node-problem-detector
    env: kube-system
spec:
  template:
    metadata:
      labels:
        run: node-problem-detector
        env: kube-system
    spec:
      containers:
      - name: node-problem-detector
        image:  '${node_problem_detector_image}'
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        volumeMounts:
        - name: log
          mountPath: /log
          readOnly: true
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
      volumes:
      - name: log
        hostPath:
          path: /var/log/
      - name: localtime
        hostPath:
          path: /etc/localtime
